from pathlib import Path


DATA_PATH = Path("data/concursos_anteriores.csv")
PROCESSED_DATA_PATH = Path("data/processed_training_data.json")
MODEL_PATH = Path("models/loteca_softmax_model.json")
NEXT_CONTEST_PATH = Path("data/proximo_concurso.csv")
OUTPUT_CARD_PATH = Path("output/cartao_loteca.csv")
OUTPUT_LOG_PATH = Path("output/antipulverizacao.log")

SEED = 42
TRAIN_RATIO = 0.8
EPOCHS = 200
LEARNING_RATE = 0.05
L2 = 0.001
LOG_EVERY = 10
EARLY_STOPPING_PATIENCE = 25
EARLY_STOPPING_MIN_DELTA = 1e-4
LR_DECAY_EVERY = 10
LR_DECAY_GAMMA = 0.98
L2_PLATEAU = 0.003

CLASS_WEIGHT_MODE = "sqrt_inv"
DUPLO_COUNT = 2
OBJECTIVE_MODE = "p13plus"
OBJECTIVE_ALPHA = 0.4
PULVERIZATION_LAMBDA = 0.02
PULVERIZATION_PENALTY_WEIGHTS = (1.0, 1.2, 0.6)
PULVERIZATION_MARKET_PENALTY_WEIGHT = 0.5
PULVERIZATION_CONTRARIAN_BONUS_WEIGHT = 0.6
PULVERIZATION_PENALTY_BUDGET_AGRESSIVE = 10.0
PULVERIZATION_PENALTY_BUDGET_ROBUSTO = 6.0
ROBUST_MIN_P13_PLUS = 0.02
OPTIMIZATION_MODE = "agressivo"
SECO_FRACO_TH = 0.45
SECO_FRACO_TOP2_TH = 0.72
SECO_MIN_ACERTO_TH = 0.33
SECO_FLIP_MARGIN_TH = 0.04
SECO_FLIP_GAP_MIN = 0.02
ANTI_PULVERIZATION_BIAS = 0.15
L1_DELTA_TH = 0.10
L1_DELTA_TH_HIGH = 0.12
L1_DELTA_TH_LOW = 0.08
DUPLO_TOPK_PAIRS = 10
DUPLO_RISK_TOPK_GAMES = 6
DUPLO_VALUE_ALPHA = 0.15
RISK_WEIGHTS = (0.55, 0.35, 0.1)
ENTROPY_COIN_TOSS_TH = 1.08
MARGIN_COIN_TOSS_TH = 0.05
MARKET_FAVORITE_MID_LOW = 0.45
MARKET_FAVORITE_MID_HIGH = 0.60
MARKET_FAVORITE_HIGH_TH = 0.70
MARKET_FAVORITE_FLIP_TH = 0.52
CONTRARIAN_MIN_P = 0.35
SENSITIVITY_SHIFTS = (0.01, 0.02, 0.05)
RUN_MANIFEST_PATH = Path("output/run_manifest.json")
VALIDATION_STRATEGY = "temporal"
